### ISSUE TITLE
dhd files are 378 but downloaded fules are 380?

### ISSUE THREAD

**Issue by rsaurav12** [anthonywww/mksld#3]
Why downloaded files are 380 while in api there are only 378 dhd images

**Comment by anthonywww** [comment]
there are 380 "dhd" images in the `@mksld_media.json` cached response, perhaps the public API is no longer returning all of them or that repo isn't parsing the json correctly? feel free to use whatever you need from this repo if it helps.

<img width="609" alt="image" src="https://github.com/user-attachments/assets/754b6fa2-428d-434c-a2fc-f08453a0218b">

**Comment by rsaurav12** [comment]
Sure, awesome work btw 👍 it is possible to categorise images acc. to the artists to separate folders?

**Comment by anthonywww** [comment]
I assume you mean something like this? Added in PR #4 and merged.

![image](https://github.com/user-attachments/assets/a0b7e01b-83fb-4773-8183-5c2308d1e75e)
